version: "3.8"

services:
  backend:
    container_name: backendContainer
    build: ./backend
    ports:
      - '3001:3001'
    networks:
      - chatwebsite

  frontend:
    container_name: frontendContainer
    build: ./frontend
    ports:
      - '3000:3000'
    networks:
      - chatwebsite
networks:
  chatwebsite:
