version: "3.8"

services:
  db:
    container_name: dbContainer
    build: ./database
    ports:
      - 3306:3306
    networks:
      - chatwebsite
    volumes:
      - chatdb:/var/lib/mysql

  backend:
    container_name: backendContainer
    depends_on:
      - db
    build: ./backend
    ports:
      - '3001:3001'
    networks:
      - chatwebsite

  frontend:
    container_name: frontendContainer
    depends_on:
      - db
    build: ./frontend
    ports:
      - '3000:3000'
    networks:
      - chatwebsite

networks:
  chatwebsite:

volumes:
  chatdb:

