version: "3.8"

services:
  db:
    container_name: dbContainer
    build:
      context: ./database
      target: testdb
    environment:
        DB_HOST: ${DB_HOST}
    ports:
      - 3306:3306
    networks:
      - chatwebsite
#    volumes:
#      - chatdb:/var/lib/mysql

  backend:
    container_name: backendContainer
    build:
      context: ./backend
      target: dev
    ports:
      - '3001:3001'
    networks:
      - chatwebsite

  frontend:
    container_name: frontendContainer
    build:
      context: ./frontend
      target: dev
    ports:
      - '3000:3000'
    networks:
      - chatwebsite

networks:
  chatwebsite:

volumes:
  chatdb:

