#dockerfile for the backend

FROM node:19.8 as base

WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production
ENV PORT=3001
EXPOSE 3001


FROM base as prod
COPY --from=base /app/node_modules ./node_modules
COPY . .
CMD ["npm", "start"]

FROM base as dev
COPY --from=base /app/node_modules ./node_modules
COPY . .
RUN npm ci --only=dev
CMD ["npm", "start"]

FROM base as testdb
COPY --from=base /app/node_modules ./node_modules
COPY . .
RUN npm ci --only=dev
CMD ["npm", "run", "testDB"]

FROM base as testbe
COPY --from=base /app/node_modules ./node_modules
COPY . .
RUN npm ci --only=dev
CMD ["npm", "run", "testBE"]