name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["Type: Bug", "Status: Pending"]

body: 
  - type: textarea
    id: describe-the-bug 
    attributes:
      label: Describe the bug 
      description: Also tell us, what did you expect to happen?
      placeholder: "A clear and concise description of the bug."
  - type: textarea
    id: steps-to-reproduce 
    attributes:
      label: Steps To Reproduce
      description: Describe the steps to reproduce the bug
      placeholder: Steps 
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
