name: Bug Report
description: File a bug report
title: "[Bug]: " 
labels: ["Type: Bug", "Status: Pending"]

body: 
  - type: textarea
    attributes:
      label: Describe the bug 
      description: Also tell us, what did you expect to happen?
      placeholder: "A clear and concise description of the bug."
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Describe the steps to reproduce the bug
      placeholder: Steps
      value: "1. "
  - type: textarea
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code.
      render: shell
  - type: textarea
    attributes:
      label: Pictures
      description: If you have any screenshots showing the bug, please place them here.
