name: Enhancement Request
description: Create a request for a new feature
title: "[New Feature]:  " 
labels: ["Type: Enhancement", "Status: Pending"]

body: 
  - type: textarea
    attributes:
      label: Describe the feature 
      description: "Describe the new feature that should be implemented."
  - type: textarea
    attributes:
      label: Prototypes
      description: If you have any UI prototypes, place them here
      placeholder: Drag and drop images here
  - type: input
    attributes:
      label: Estimated time to implement this new feature
