FROM mysql:5-debian as base

ENV MYSQL_ALLOW_EMPTY_PASSWORD=0

EXPOSE 3306

FROM base as dev
COPY database-init/1.init.sql /docker-entrypoint-initdb.d/1.init.sql
VOLUME /var/lib/mysql
CMD ["mysqld"]


FROM base as testdb
COPY ./database-init /docker-entrypoint-initdb.d
CMD ["mysqld"]



