name: "Main Pipeline"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build_Backend:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build Node
        run:
          docker build -t server .
        working-directory: backend
      
      - name: Push Image to GitHub Container Registry
        run:
          docker push ghcr.io/wahhajclassprojects/cmpt353/server:latest
  
    
